# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=255)),
                ('Alias', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_with', to='main.User')),
                ('users', models.ManyToManyField(related_name='friends', to='main.User')),
            ],
        ),
    ]
