# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171120_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Alias',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(related_name='_user_items_+', to='main.User'),
        ),
    ]
